[pytest]
addopts = -v --html=report.html --self-contained-html --tracing=retain-on-failure --screenshot=only-on-failure --video=retain-on-failure
testpaths = tests
markers =
    smoke: critical smoke tests
    regression: regression test cases
    readonly: read-only test cases